defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *defaults
  database: diet_app_development

test:
  <<: *defaults
  database: diet_app_test

production:
  <<: *defaults
  database: diet_app_production